version: '3.8'

services:
  hiddibot:
    build: .
    container_name: hiddibot_app
    restart: always
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./cache_avatars:/app/cache_avatars
      - ./static/uploads:/app/static/uploads
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=${PORT:-5000}
      - PANEL_PORT=${PANEL_PORT:-5000}
