version: '3.8'

services:
  hiddibot:
    build: .
    container_name: hiddibot_app
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./cache_avatars:/app/cache_avatars
      - ./static/uploads:/app/static/uploads
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=5000
